# Generated by Django 5.1.5 on 2025-02-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='publication_sing',
            new_name='is_publication',
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='count_of_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
