# Generated by Django 5.1.5 on 2025-02-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_publication_sing_blog_is_publication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
